pages:
  - name: ホーム - 未来
    path: /2025-01-30
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2024-12-20
  - name: 出走表
    path: /races/1d2cd740-2900-4175-a207-b0b079b817ec/race-card
  - name: オッズ - 締め切り前
    path: /races/17b5bcf3-902f-4eb7-b79d-c557079c49da/odds
  - name: オッズ - 締め切り後
    path: /races/09ac7bdb-41e8-4a0e-adf4-83fe061d269d/odds
  - name: 結果
    path: /races/70d89e2a-9bd7-4e15-afb2-665c19561c12/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
